export default {
    products: [
        {
            _id: '1',
            name: 'BBA Fashion Majica',
            category: 'Majica',
            image: './images/product-1.jpg',
            price: 1000,
            brand: 'BBA Fashion',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'BBA Fashion Maskembaj Haljina',
            category: 'Haljina',
            image: './images/product-2.jpg',
            price: 5000,
            brand: 'BBA Fashion',
            rating: 3.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '3',
            name: 'BBA Fashion Haljina Svecana',
            category: 'Haljina',
            image: './images/product-3.jpg',
            price: 1000,
            brand: 'BBA Fashion',
            rating: 5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '4',
            name: 'BBA Fashion Bluza Dugi Rukav',
            category: 'Bluza',
            image: './images/product-4.jpg',
            price: 2599,
            brand: 'BBA Fashion',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '5',
            name: 'BBA Fashion Bluza Na Preklop',
            category: 'Bluza',
            image: './images/product-5.jpg',
            price: 3000,
            brand: 'BBA Fashion',
            rating: 4,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '6',
            name: 'BBA Fashion Maskembal Haljina',
            category: 'Haljina',
            image: '/images/product-6.jpg',
            price: 10000,
            brand: 'BBA Fashion',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
    ]
}